---
apiVersion: v1
kind: Secret
metadata:
  name: chiquinha-cred
  namespace: monitoring
data:
  INFLUX_DB: ZmxvcmluZGFib3g=
  INFLUX_HOST: aW5mbHV4ZGI=
  INFLUX_PORT: ODA4Ng==
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chiquinha-config
  namespace: monitoring  
data:
  INFLUX_ENABLE: "false"
  SPEEDTEST_TZ: "America/Sao_Paulo"
  SPEEDTEST_INTERVAL: "30m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chiquinha
  name: chiquinha
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chiquinha
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chiquinha
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: chiquinha-cred
        - configMapRef:
            name: chiquinha-config
        image: docker.io/uknbr/florindabox-chiquinha:latest
        imagePullPolicy: Always
        name: chiquinha
        resources:
          requests:
            memory: 24Mi
            cpu: 50m
          limits:
            memory: 256Mi
            cpu: 500m
      nodeSelector:
        type: master
      dnsPolicy: ClusterFirst
      restartPolicy: Always