---
app_port: 8080
app_name: hello-florinda
app_rs: 4
app_ns: hello
app_image: myoung34/armhf-hello-kubernetes:latest
app_url: hello.192.168.15.36.traefik.me
app_msg: FlorindaBox is running!
app_node: worker
kubeconfig: /home/pi/.kube/config