# Provide a custom message
message: ""

# Remember to set service.type=ClusterIP if you are using an ingress
ingress:
  configured: false
  rewritePath: true
  pathPrefix: ""

service:
  type: LoadBalancer
  port: 80

deployment:
  replicaCount: 2
  container:
    image:
      repository: "myoung34/armhf-hello-kubernetes"
      tag: "latest"
      pullPolicy: IfNotPresent
    port: 8080

  nodeSelector: {}

  resources: {}

  tolerations: []

  affinity: {}
