---

- name: Install Helm
  unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-arm.tar.gz
    dest: /usr/local/bin
    extra_opts:
    - --strip=1
    - --wildcards
    - '*/helm'
    remote_src: yes
    mode: 0755

- name: Install Kubectl
  get_url:
    url: https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/arm/kubectl
    dest: /usr/bin/kubectl
    mode: 0755

- name: Install k8s modules
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes
    executable: /usr/bin/pip3