---
  - name: Update apt cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
    tags:
      - package

  - name: Upgrade packages
    apt:
      upgrade: dist
      force_apt_get: yes
    tags:
      - package

  - name: Install basic packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages:
        - htop
        - dos2unix
        - net-tools
        - git
        - jq
        - aptitude
        - bash-completion
        - python3
        - python3-pip
    tags:
      - package

  - name: Set timezone
    file:
      src: /usr/share/zoneinfo/America/Sao_Paulo
      dest: /etc/localtime
      owner: root
      group: root
      state: link
    notify:
      - update timezone
