apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: starkandwayne/hello-multiarch:cat-log
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure