---
volume_data: /data
volume_size: 500Mi
helm_chart_url: https://mojo2600.github.io/pihole-kubernetes/
helm_chart_name: pihole
helm_chart_version: 2.5.4
target_namespace: pihole
target_nodes:
  - worker1
  - worker2
pihole_dns1: 208.67.222.222
pihole_dns2: 8.8.8.8
pihole_tz: America/Sao_Paulo
pihole_password: YWRtaW4= # password=admin